---
baseURL: https://maelvls.dev/
languageCode: en-us
title: maelvls dev blog
theme: hugo-vitae
googleAnalytics: "UA-88710120-3"

# NOTE: I'm not using disqus. I'm using utterance.us. The short name for
# utterance.us is the Github repo slug, for example:
# maelvls/maelvls.github.io.
disqusShortname: maelvls/maelvls.github.io

algolia:
  index: "maelvls.dev"
  appID: "3XE19IWIB0"
  # key: "" (set in .envrc using ALGOLIA_WRITE_KEY)

outputs:
  home: [HTML, RSS, algolia]
outputFormats:
  algolia:
    baseName: algolia # _default/something.algolia.json
    isPlainText: true
    mediaType: application/json
    notAlternative: true

paginate: 1000
pygmentsstyle: abap # will deprecate soon since we use goldmark now
pygmentsUseClasses: true # hugo gen chromastyles --style=abap >> static/css/maelvls.css
pygmentscodefences: true
pygmentscodefencesguesssyntax: true
taxonomies:
  tag: tags
  series: series

params:
  algolia:
    vars: [title, summary, date, publishdate, expirydate, permalink]
    params: [categories, tags]

  mainSections: ["2020", "2019"]

  # Custom css is expected to be in static/css/.
  customCSS: maelvls.css
  subtitle: Systems software engineer. I write mostly about Kubernetes and Go. [About](/about)
  avatar: /img/mael.jpg
  disableDisqusTypes:
    - page
  social:
    - name: Github
      icon: fab fa-github
      url: "https://github.com/maelvls"
    - name: Twitter
      icon: fab fa-twitter
      url: "https://twitter.com/maelvls"

# menu:
#   main:
#     - name: Home
#       url: /
#       weight: 1
#     - name: About
#       url: /about
#       weight: 3

# Specifics to Hugo.
markup:
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute: true
      autoHeadingID: true
      autoHeadingIDType: github
    renderer:
      hardWraps: false
      unsafe: true # so that I can use <img>
      xHTML: false
  highlight:
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: monokai
    tabWidth: 4
  tableOfContents:
    endLevel: 3
    ordered: true
    startLevel: 2

services:
  rss:
    limit: 0
