name: publish-hugo-gh-pages
on:
  push:
    branches: source
jobs:
  publish:
    runs-on: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Hugo setup
      uses: peaceiris/actions-hugo@v2.4.5
    - name: GitHub Pages
      if: success()
      uses: crazy-max/ghaction-github-pages@v1.2.5
      env:
        # The GITHUB_TOKEN already given for running github actions
        # is not sufficient. It allows me to push to master but for
        # some reason it won't trigger a github-pages "build & push
        # to CDN". I had to create a personnal access token with
        # the 'repo' scope.
        GITHUB_PAT: ${{ secrets.GITHUB_PAT }}
      with:
        # repo: maelvls/maelvls.github.io
        target_branch: master
        keep_history: false
        allow_empty_commit: true
        build_dir: publish
        # Write the given domain name to the CNAME file
        # fqdn: maelvls.dev
