name: CI
on:
  push:
    branches: source
jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Hugo setup
      uses: peaceiris/actions-hugo@v2.4.5
    - name: GitHub Pages
      uses: crazy-max/ghaction-github-pages@v1.2.5
      env:
        # The GITHUB_TOKEN already given for running github actions
        # is not sufficient. It allows me to push to master but for
        # some reason it won't trigger a github-pages "build & push
        # to CDN".
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN2 }}
      with:
        # repo: maelvls/maelvls.github.io
        target_branch: master
        keep_history: false
        allow_empty_commit: true
        build_dir: publish
        committer_name: Maël Valais
        committer_email: mael.valais@gmail.com
        commit_message: update
        # Write the given domain name to the CNAME file
        fqdn: maelvls.dev
